/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOauthLogoutRouteImport } from './routes/api/oauth/logout'
import { Route as ApiOauthLoginRouteImport } from './routes/api/oauth/login'
import { Route as ApiOauthCallbackRouteImport } from './routes/api/oauth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthLogoutRoute = ApiOauthLogoutRouteImport.update({
  id: '/api/oauth/logout',
  path: '/api/oauth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthLoginRoute = ApiOauthLoginRouteImport.update({
  id: '/api/oauth/login',
  path: '/api/oauth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthCallbackRoute = ApiOauthCallbackRouteImport.update({
  id: '/api/oauth/callback',
  path: '/api/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/oauth/login': typeof ApiOauthLoginRoute
  '/api/oauth/logout': typeof ApiOauthLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/oauth/login': typeof ApiOauthLoginRoute
  '/api/oauth/logout': typeof ApiOauthLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/oauth/login': typeof ApiOauthLoginRoute
  '/api/oauth/logout': typeof ApiOauthLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/oauth/callback'
    | '/api/oauth/login'
    | '/api/oauth/logout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/oauth/callback' | '/api/oauth/login' | '/api/oauth/logout'
  id:
    | '__root__'
    | '/'
    | '/api/oauth/callback'
    | '/api/oauth/login'
    | '/api/oauth/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiOauthCallbackRoute: typeof ApiOauthCallbackRoute
  ApiOauthLoginRoute: typeof ApiOauthLoginRoute
  ApiOauthLogoutRoute: typeof ApiOauthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/logout': {
      id: '/api/oauth/logout'
      path: '/api/oauth/logout'
      fullPath: '/api/oauth/logout'
      preLoaderRoute: typeof ApiOauthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/login': {
      id: '/api/oauth/login'
      path: '/api/oauth/login'
      fullPath: '/api/oauth/login'
      preLoaderRoute: typeof ApiOauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/callback': {
      id: '/api/oauth/callback'
      path: '/api/oauth/callback'
      fullPath: '/api/oauth/callback'
      preLoaderRoute: typeof ApiOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiOauthCallbackRoute: ApiOauthCallbackRoute,
  ApiOauthLoginRoute: ApiOauthLoginRoute,
  ApiOauthLogoutRoute: ApiOauthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
